import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from '@/components/Navbar'

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <div className='main'>
          <div className='gradient' />
        </div>
        <div className="relative app">
          <Navbar />
          <main className="absolute top-0 left-0 right-0">{children}</main>
        </div>
      </body>
    </html>
  );
}